language: python
python: 2.7
install:
  - sudo apt-get -qq install libfreetype6-dev liblcms1-dev libwebp-dev
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test && bin/code-analysis
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
